name: Build and Commit Minified JS

on:
  push:
    branches: [ main ]
  # Optional: trigger only on version tags like v1.0.0
  # push:
  #   tags:
  #     - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.0

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build minified file
        run: npm run build

      - name: Commit minified output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cleanr.min.js
          git commit -m "chore: auto-build minified file [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
